apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.certmanager.name }}
  labels:
    "cert-manager.io/disable-validation": "true"    
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.application.name }}
